$(document).ready(function(){
    $("#hover").click(function(){
        $("#container").load("./hover.html");
    });
    $("#down").click(function(){
        $("#container").load("./down.html");
    });
    $("#enter").click(function(){
        $("#container").load("./enter.html");
    });
    $("#over").click(function(){
        $("#container").load("./over.html");
    });
    $("#recu").click(function(){
        $("#container").load("./recu.html");
    });
    $("#alt").click(function(){
        $("#container").load("./alt.html");
    });
    $("#add").click(function(){
        $("#container").load("./add.html");
    });
    $("#remove").click(function(){
        $("#container").load("./remove.html");
    });
    $("#text").click(function(){
        $("#container").load("./text.html");
    });
    $("#with").click(function(){
        $("#container").load("./with.html");
    });
    $("#remove_remove").click(function(){
        $("#container").load("./remove_remove.html");
    });
    $("#key").click(function(){
        $("#container").load("./key.html");
    });
    $("#fade").click(function(){
        $("#container").load("./fade.html");
    });
    $("#slide").click(function(){
        $("#container").load("./slide.html");
    });
    $("#keypress").click(function(){
        $("#container").load("./keypress.html");
    });
    //efeitos das paginas
    $("#hover_exemplo").hover
});